name: CI and CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

defaults:
  run:
      shell: bash  

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 8  
          distribution: zulu
          architecture: x64
          overwrite-settings: false
          
      - uses: actions/checkout@v4

      - name: Run Unit tests
        run: mvn clean test
        
  publish-to-exchange:
    name: Publish to exchange
    needs:
      - unit-tests
    uses: ./.github/workflows/publish-to-exchange.yaml
    with:
      gitRef: ${{ vars.GITHUB_SHA }}
    secrets: inherit
  
  deployToNonprod:
    name: Deploy To ${{ matrix.target }}
    needs: 
      - publish-to-exchange
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        target: [ Dev, UAT ]
    uses: ./.github/workflows/deploy.yaml
    with:
      targetEnv: ${{ matrix.target }}
    secrets: inherit
