name: CI and CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

defaults:
  run:
    shell: bash  

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 8  
          distribution: zulu
          architecture: x64
          overwrite-settings: false
          
      - uses: actions/checkout@v4

      - name: Run Unit tests
        run: mvn clean test
        
  publish-to-artifactory:
    name: Publish to artifactory
    needs:
      - unit-tests
    uses: ./.github/workflows/publish-to-exchange.yaml
    with:
      gitRef: ${{ vars.GITHUB_SHA }}
    secrets: inherit

  environments-to-deploy:
    runs-on: ubuntu-latest
    name: Environments To Deploy
    needs:
      - unit-tests
    outputs:
      envsToDeploy: ${{ steps.envsToDeploy.outputs.result }}
    env:
      EVENT_NAME: ${{ github.event_name }}
    steps:
      - name: Set Environments to deploy
        id: envsToDeploy
        run: |
          if [ "$EVENT_NAME" == "pull_request" ]; then
            echo "result=[Dev]" >> "$GITHUB_OUTPUT"
          else if [ "$EVENT_NAME" == "push" ]; then
            echo "result=[Dev, UAT]" >> "$GITHUB_OUTPUT"
          fi
      
  deploy-to-nonprod:
    name: Deploy to ${{ matrix.target }}
    needs: 
      - publish-to-artifactory
      - environments-to-deploy
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        target: ${{ fromJSON(needs.environments-to-deploy.outputs.envsToDeploy) }}
    uses: ./.github/workflows/deploy.yaml
    with:
      targetEnv: ${{ matrix.target }}
    secrets: inherit

