name: CI only

on:
  push:
    branches:
      - main
      - feature/*

defaults:
  run:
      shell: bash  

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo"
        run: echo 'hello world!!'

  unit-tests:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 8
          distribution: zulu
          architecture: x64
          overwrite-settings: false

      - name: Run Unit tests
        run: mvn clean test
        
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    needs: 
      - unit-tests
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 8
          distribution: zulu
          architecture: x64
          overwrite-settings: false
          
      - name: Deploy to Dev
        run: mvn clean package 
  
