name: CI and CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

defaults:
  run:
      shell: bash  

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 8  
          distribution: zulu
          architecture: x64
          overwrite-settings: false
          
      - uses: actions/checkout@v2

      - name: Run Unit tests
        run: mvn clean test
        
  publish-to-exchange:
    runs-on: ubuntu-latest
    name: Publish to exchange
    needs:
      - unit-tests
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 8
          distribution: zulu
          architecture: x64
          overwrite-settings: false
          
      - uses: actions/checkout@v2

      - name: Publish To Exchange
        env:
          EXCHANGE_CLIENT_ID: ${{ secrets.EXCHANGE_CLIENT_ID }}
          EXCHANGE_CLIENT_SECRET: ${{ secrets.EXCHANGE_CLIENT_SECRET }}
        run: |
            mvn clean deploy \
                -DskipTests \
                --settings .github/mvn-config/settings.xml \
                -Dexchange.clientId=$EXCHANGE_CLIENT_ID \
                -Dexchange.clientSecret=$EXCHANGE_CLIENT_SECRET
  
  deploy:
    name: Deploy To ${{ matrix.target }}
    needs: 
      - publish-to-exchange
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        target: [ Dev, UAT ]
    uses: ./.github/workflows/deploy.yml
    with:
      target-env: ${ { matrix.target } }
    secrets: inherit
