name: CI only

on:
  push:
    branches:
      - main
      - feature/*

jobs:

  hello-world:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: "Echo"
        run: echo 'hello world!!'

  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 8.0.232
          distribution: zulu
          architecture: x64
          overwrite-settings: false
    
