name: CI only

on:
  push:
    branches:
      - main
      - feature/*

defaults:
  run:
      shell: bash  

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo"
        run: echo 'hello world!!'

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 8
          distribution: zulu
          architecture: x64
          overwrite-settings: false

      - name: Check java version
        run: java -version

      - name: Check maven version
        run: mvn --version

  echo-java-version:
    runs-on: ubuntu-latest
    needs: 
      - setup
    steps:
      - run: java --version
  
  echo-mvn-version:
    runs-on: ubuntu-latest
    needs: 
      - setup
    steps:
      - run: mvn --version
