name: Create production release from commit

on:
  workflow_call:
    inputs:
      gitRef:
        required: true
        type: string
        description: The branch, tag or SHA to checkout
    secrets:
      EXCHANGE_CLIENT_ID:
        required: true
      EXCHANGE_CLIENT_SECRET:
        required: true  
  push:
    branches:
      - feature/*
 
defaults:
  run:
    shell: bash
    
jobs:

  pom-semver-without-snapshot:
    runs-on: ubuntu-latest
    name: Get Pom Version
    outputs:
      newPomVersion: ${{ steps.removeSnapshot.outputs.newPomVersion }}
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 8  
          distribution: zulu
          architecture: x64
          overwrite-settings: false
          
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.gitRef || github.ref_name }}
      
      - id: removeSnapshot
        name: Remove SNAPSHOT
        run: |
            mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false
            newPomVersion=$(mvn help:evaluate '-Dexpression=project.version' -q -DforceStdout)
            echo "New version after removing SNAPSHOT = $newPomVersion"
            echo "newPomVersion=$newPomVersion" >> "$GITHUB_OUTPUT"    

  get-commit-sha-for-ref:
    runs-on: ubuntu-latest
    name: Get Commit SHA
    outputs:
      sha: ${{ steps.getSha.outputs.result }}
    steps:
      - name: Get SHA hash of gitRef
        id: getSha
        uses: actions/github-script@v5
        with:
          script: |
            const commit = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: '${{ inputs.gitRef || github.ref_name }}'
            })
            const sha = commit.data.sha
            console.log(`Got commit SHA: ${sha}`)
            return sha.toString()
  create-git-tag:
    runs-on: ubuntu-latest
    name: Create tag
    needs: 
      - pom-semver-without-snapshot
      - get-commit-sha-for-ref
    env:
      TAG_NAME: v${{ needs.pom-semver-without-snapshot.outputs.newPomVersion }}
      TAG_SHA: ${{ needs.get-commit-sha-for-ref.outputs.sha }}
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            console.log(`Creating tag with name: ${process.env.TAG_NAME} on SHA: ${process.env.TAG_SHA}`)
            const createRefResponse = await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${process.env.TAG_NAME}`,
              sha: `${process.env.TAG_SHA.replace('"', '')}`
            })
            console.log(createRefResponse)
