name: Create production release from commit

on:
  workflow_dispatch:
    inputs:
      gitRef:
        required: true
        type: string
        description: The branch, tag or SHA to checkout
      withVersion:
        required: false
        type: string
        description: |
          Version number of the artifact to publish to exchange. Or the version already exists in exchange. Defaults to POM version (removing SNAPSHOT)
        
defaults:
  run:
    shell: bash
    
jobs:

  get-commit-sha-for-ref:
    runs-on: ubuntu-latest
    name: Get Commit SHA
    outputs:
      sha: ${{ steps.getSha.outputs.result }}
    steps:
      - name: Get SHA hash of gitRef
        id: getSha
        uses: actions/github-script@v5
        with:
          script: |
            const commit = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: '${{ inputs.gitRef || github.ref_name }}'
            })
            const sha = commit.data.sha
            console.log(`Got commit SHA: ${sha}`)
            return sha.toString()

  pom-semver-without-snapshot:
    runs-on: ubuntu-latest
    if: "${{ inputs.withVersion == '' }}"
    name: Get Pom Version
    needs:
      - get-commit-sha-for-ref
    outputs:
      newPomVersion: ${{ steps.removeSnapshot.outputs.newPomVersion }}
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 8  
          distribution: zulu
          architecture: x64
          overwrite-settings: false
          
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.gitRef || github.ref_name }}
      
      - id: removeSnapshot
        name: Remove SNAPSHOT
        run: |
            mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false
            newPomVersion=$(mvn help:evaluate '-Dexpression=project.version' -q -DforceStdout)
            echo "New version after removing SNAPSHOT = $newPomVersion"
            echo "newPomVersion=$newPomVersion" >> "$GITHUB_OUTPUT" 
            
  create-git-tag:
    runs-on: ubuntu-latest
    name: Create tag
    needs: 
      - pom-semver-without-snapshot
      - get-commit-sha-for-ref
    if: ${{ always() && !failure() && !cancelled() }}
    env:
      TAG_NAME: v${{ inputs.withVersion || needs.pom-semver-without-snapshot.outputs.newPomVersion }}
      TAG_SHA: ${{ needs.get-commit-sha-for-ref.outputs.sha }}
    outputs:
      tagName: ${{ vars.TAG_NAME }}
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            console.log(`Creating tag with name: ${process.env.TAG_NAME} on SHA: ${process.env.TAG_SHA}`)
            const createRefResponse = await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${process.env.TAG_NAME}`,
              sha: `${process.env.TAG_SHA.replaceAll('"', '')}`
            })
            console.log(`Tag created: ${createRefResponse.data.url}`)

  publish-to-artifactory:
    name: Publish to artifactory
    needs:
      - create-git-tag
    uses: ./.github/workflows/publish-to-exchange.yaml
    with:
      gitRef: ${{ needs.create-git-tag.outputs.tagName }}
      removeSnapshotFromVersion: true
      withVersion: ${{ inputs.withVersion || needs.pom-semver-without-snapshot.outputs.newPomVersion }}
    secrets: inherit

  deployToProd:
    name: Deploy to ${{ matrix.target }}
    needs: 
      - publish-to-artifactory
    uses: ./.github/workflows/deploy.yaml
    with:
      targetEnv: Production
    secrets: inherit
    
