name: Create production release from commit

on:
  workflow_call:
    inputs:
      gitRef:
        required: true
        type: string
        description: The branch, tag or SHA to checkout
    secrets:
      EXCHANGE_CLIENT_ID:
        required: true
      EXCHANGE_CLIENT_SECRET:
        required: true  
  push:
    branches:
      - feature/*
 
defaults:
  run:
    shell: bash
    
jobs:

  pom-semver-without-snapshot:
    runs-on: ubuntu-latest
    name: Get Pom Version
    outputs:
      newPomVersion: ${{ steps.removeSnapshot.outputs.newPomVersion }}
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 8  
          distribution: zulu
          architecture: x64
          overwrite-settings: false
          
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.gitRef }}
      
      - id: removeSnapshot
        name: Remove SNAPSHOT
        run: |
            mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false
            newPomVersion=$(mvn help:evaluate '-Dexpression=project.version' -q -DforceStdout)
            echo "New version after removing SNAPSHOT = $newPomVersion"
            echo "newPomVersion=$newPomVersion" >> "$GITHUB_OUTPUT"    
  
  create-git-tag:
    runs-on: ubuntu-latest
    name: Create tag
    needs: 
      - pom-semver-without-snapshot
    env:
      gitRef: :{{ inputs.gitRef }}
      tagVersion: v${{needs.pom-semver-without-snapshot.outputs.newPomVersion}}
    steps:
      - name: Get SHA hash of gitRef
        uses: actions/github-script@v5
        with:
          script: |
            const commit = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `${gitRef}`
            })
            console.log(commit)
 
