name: Deployment to production

on:
  push:
    branches:
      - release/*
  workflow_call:
    inputs:
      withVersion:
        type: string
        required: true
      commitSHA:
        type: string
        required: true
        
defaults:
  run:
    shell: bash
    
jobs:

  get-pom-semver:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    name: Get Pom Version
    outputs:
      pomVersion: ${{ steps.getPomVersion.outputs.pomVersion }}
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 8  
          distribution: zulu
          architecture: x64
          overwrite-settings: false
          
      - uses: actions/checkout@v4
        
      - id: getPomVersion
        name: Get Pom Version
        run: |
            pomVersion=$(mvn help:evaluate '-Dexpression=project.version' -q -DforceStdout)
            echo "Version retrieved from POM: $pomVersion"
            echo "pomVersion=$pomVersion" >> "$GITHUB_OUTPUT" 
            
  create-git-tag:
    runs-on: ubuntu-latest
    name: Create tag
    needs: 
      - get-pom-semver
    if: |
      always() &&
      (needs.get-pom-semver.result == 'success' || needs.get-pom-semver.result == 'skipped')
    env:
      TAG_NAME: v${{ inputs.withVersion || needs.get-pom-semver.outputs.newPomVersion }}
      TAG_SHA: ${{ inputs.commitSHA || github.sha }}
    outputs:
      tagName: ${{ vars.TAG_NAME }}
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            console.log(`Creating tag with name: ${process.env.TAG_NAME} on SHA: ${process.env.TAG_SHA}`)
            const createRefResponse = await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${process.env.TAG_NAME}`,
              sha: process.env.TAG_SHA
            })
            console.log(`Tag created: ${createRefResponse.data.url}`)
            return process.env.TAG_NAME;

#Teh following two jobs (publish to artifactory and deploy) 
# should ideally be picked from the reusable workflow. 
# But it seems like there is a limit to the nesting of these.

  # publish-to-artifactory:
  
  #   name: Publish to artifactory
  #   needs:
  #     - create-git-tag
  #   uses: ./.github/workflows/publish-to-exchange.yaml
  #   with:
  #     gitRef: ${{ needs.create-git-tag.outputs.tagName }}
  #   secrets: inherit
  
  # deployToProd:
  #   name: Deploy to Production
  #   needs: 
  #     - publish-to-artifactory
  #   uses: ./.github/workflows/deploy.yaml
  #   with:
  #     targetEnv: Production
  #   secrets: inherit
    
  publish-to-exchange:
    runs-on: ubuntu-latest
    name: Publish to exchange
    needs:
          - create-git-tag
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.create-git-tag.outputs.tagName }}
          
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 8
          distribution: zulu
          architecture: x64
          overwrite-settings: false
            
      - name: Publish To Exchange
        env:
          EXCHANGE_CLIENT_ID: ${{ secrets.EXCHANGE_CLIENT_ID }}
          EXCHANGE_CLIENT_SECRET: ${{ secrets.EXCHANGE_CLIENT_SECRET }}
        run: |
            mvn clean deploy \
                -DskipTests \
                --settings .github/mvn-config/settings.xml \
                -Dexchange.clientId=$EXCHANGE_CLIENT_ID \
                -Dexchange.clientSecret=$EXCHANGE_CLIENT_SECRET


  deploy:
    runs-on: ubuntu-latest
    name: Deploy To Production
    needs:
      - publish-to-exchange
      - create-git-tag
    environment: Production
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 8
          distribution: zulu
          architecture: x64
          overwrite-settings: false
          
      - uses: actions/checkout@v4
        with: 
          ref: ${{ needs.create-git-tag.outputs.tagName }}
          
      - name: Deploy to Production
        env:
          EXCHANGE_CLIENT_ID: ${{ secrets.EXCHANGE_CLIENT_ID }}
          EXCHANGE_CLIENT_SECRET: ${{ secrets.EXCHANGE_CLIENT_SECRET }}
          DEPLOY_ENV: ${{ vars.DEPLOY_ENV }}
          MULE_ENV: ${{ vars.MULE_ENV }}
          DEPLOY_TARGET: ${{ vars.DEPLOY_TARGET }}
          MAVEN_SETTINGS_SERVER_ID: ${{ vars.MAVEN_SETTINGS_SERVER_ID }}
          DEPLOY_REPLICAS: ${{ vars.DEPLOY_REPLICAS }}
          DEPLOY_VCORES: ${{ vars.DEPLOY_VCORES }}
        run: | 
            mvn clean deploy -DskipTests \
                -DmuleDeploy \
                --settings .github/mvn-config/settings.xml \
                -Ddeploy.env=$DEPLOY_ENV \
                -Dmule.env=$MULE_ENV \
                -Ddeploy.target=$DEPLOY_TARGET \
                -Dmvnsettings.serverid=$MAVEN_SETTINGS_SERVER_ID \
                -Ddeploy.replicas=$DEPLOY_REPLICAS \
                -Ddeploy.vCores=$DEPLOY_VCORES \
                -Dexchange.clientId=$EXCHANGE_CLIENT_ID \
                -Dexchange.clientSecret=$EXCHANGE_CLIENT_SECRET
