name: CD only

on:
  workflow_call:
    inputs:
      targetEnv:
        required: true
        type: string
    secrets:
      EXCHANGE_CLIENT_ID:
        required: true
      EXCHANGE_CLIENT_SECRET:
        required: true  

defaults:
  run:
      shell: bash  

jobs:

  deploy:
    runs-on: ubuntu-latest
    name: Deploy To ${{ inputs.targetEnv }}
    environment: ${{ inputs.targetEnv }}
    needs: 
      - publish_to_exchange
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 8
          distribution: zulu
          architecture: x64
          overwrite-settings: false
          
      - uses: actions/checkout@v2
          
      - name: Deploy to ${{ inputs.targetEnv }}
        env:
          EXCHANGE_CLIENT_ID: ${{ secrets.EXCHANGE_CLIENT_ID }}
          EXCHANGE_CLIENT_SECRET: ${{ secrets.EXCHANGE_CLIENT_SECRET }}
          DEPLOY_ENV: ${{ vars.DEPLOY_ENV }}
          MULE_ENV: ${{ vars.MULE_ENV }}
          DEPLOY_TARGET: ${{ vars.DEPLOY_TARGET }}
          MAVEN_SETTINGS_SERVER_ID: ${{ vars.MAVEN_SETTINGS_SERVER_ID }}
          DEPLOY_REPLICAS: ${{ vars.DEPLOY_REPLICAS }}
          DEPLOY_VCORES: ${{ vars.DEPLOY_VCORES }}
        run: | 
            mvn clean deploy -DskipTests \
                -DmuleDeploy \
                --settings .github/mvn-config/settings.xml \
                -Ddeploy.env=$DEPLOY_ENV \
                -Dmule.env=$MULE_ENV \
                -Ddeploy.target=$DEPLOY_TARGET \
                -Dmvnsettings.serverid=$MAVEN_SETTINGS_SERVER_ID \
                -Ddeploy.replicas=$DEPLOY_REPLICAS \
                -Ddeploy.vCores=$DEPLOY_VCORES \
                -Dexchange.clientId=$EXCHANGE_CLIENT_ID \
                -Dexchange.clientSecret=$EXCHANGE_CLIENT_SECRET
