name: Publish to exchange

on:
  workflow_call:
    inputs:
      gitRef:
        required: true
        type: string
        description: The branch, tag or SHA to checkout
      
      removeSnapshotFromVersion:
        required: false
        type: boolean
        default: false
        description: If 'SNAPSHOT' needs to be removed from version before publishing to exchange
      
      withVersion:
        required: false
        type: string
        description: Verison to use while publishing to exchange. Will be derived from pom if not provided

    secrets:
      EXCHANGE_CLIENT_ID:
        required: true
      EXCHANGE_CLIENT_SECRET:
        required: true  

defaults:
  run:
      shell: bash  

jobs:

  publish-to-exchange:
    runs-on: ubuntu-latest
    name: Publish to exchange
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.gitRef }}
          
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 8
          distribution: zulu
          architecture: x64
          overwrite-settings: false

      - name: Set version in pom
        env:
          REMOVE_SNAPSHOT: ${{ inputs.removeSnapshotFromVersion }}
          OVERRIDE_VERSION: ${{ inputs.withVersion }}
        run: |
            if [ -z "$OVERRIDE_VERSION" ]; then mvn versions:set -DnewVersion=${OVERRIDE_VERSION}
            elif [ "$OVERRIDE_VERSION" == true ]; then mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false
            fi
            newPomVersion=$(mvn help:evaluate '-Dexpression=project.version' -q -DforceStdout)
            echo "POM Version that will be published = $newPomVersion"
            
      - name: Publish To Exchange
        env:
          EXCHANGE_CLIENT_ID: ${{ secrets.EXCHANGE_CLIENT_ID }}
          EXCHANGE_CLIENT_SECRET: ${{ secrets.EXCHANGE_CLIENT_SECRET }}
        run: |
            mvn clean deploy \
                -DskipTests \
                --settings .github/mvn-config/settings.xml \
                -Dexchange.clientId=$EXCHANGE_CLIENT_ID \
                -Dexchange.clientSecret=$EXCHANGE_CLIENT_SECRET
